---
- delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: create the argo namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argo

    - name: create the argo events namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argo-events

    - name: install argo
      kubernetes.core.k8s:
        state: present
        src: install.yaml

    - name: create argo-executor role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: argo-executor
            namespace: "{{ argo_ns }}"
          rules:
            - apiGroups:
                - argoproj.io
              resources:
                - workflowtaskresults
              verbs:
                - create
                - delete
                - apply
                - patch

    - name: create the argo-executor service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: argo-executor
            namespace: "{{ argo_ns }}"

    - name: create the argo-executor role-binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ClusterRoleBinding
          metadata:
            name: argo-executor-binding
            namespace: "{{ argo_ns }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: argo-executor
            namespace: "{{ argo_ns }}"
          subjects:
            - kind: ServiceAccount
              name: argo-executor
              namespace: "{{ argo_ns }}"

    - name: install argo-events
      kubernetes.core.k8s:
        state: present
        src: argo_events_install.yaml

    - name: install argo-events eventbus
      kubernetes.core.k8s:
        state: present
        src: argo_events_eventbus_install.yaml

    - name: install argo-events sensor rbac
      kubernetes.core.k8s:
        state: present
        src: argo_events_sensor_rbac.yaml
