---
- name: Add CORS ingresses
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "discoenv"
        namespace: "{{ ns }}"
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          nginx.ingress.kubernetes.io/cors-max-age: "86400"
          nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "GET,POST,OPTIONS"
          nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range"
          nginx.ingress.kubernetes.io/cors-expose-headers: "Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range"
      spec:
        ingressClassName: nginx
        rules:
          - host: "{{ de_hostname }}"
            http:
              paths:
                - path: "/anon-files"
                  pathType: Prefix
                  backend:
                    service:
                      name: kifshare
                      port:
                        number: 80
                - path: "/dl"
                  pathType: Prefix
                  backend:
                    service:
                      name: kifshare
                      port:
                        number: 80
                - path: "/terrain"
                  pathType: Prefix
                  backend:
                    service:
                      name: terrain
                      port:
                        number: 80
                - path: /job
                  pathType: Prefix
                  backend:
                    service:
                      name: job-status-listener
                      port:
                        number: 80
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: sonora
                      port:
                        number: 80

- name: Add agave-callback ingress
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: agave-callback
        namespace: "{{ ns }}"
        annotations:
          # traefik.ingress.kubernetes.io/router.entrypoints: web
          nginx.ingress.kubernetes.io/rewrite-target: /callbacks/agave-job
      spec:
        ingressClassName: nginx
        rules:
          - host: "{{ de_hostname }}"
            http:
              paths:
                - path: /de/agave-cb
                  pathType: Prefix
                  backend:
                    service:
                      name: apps
                      port:
                        number: 80

- name: set up the portal ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: portal-ingress
        namespace: "{{ ns }}"
        annotations:
          nginx.ingress.kubernetes.io/server-snippets: |
            location / {
              proxy_set_header Upgrade $http_upgrade;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-Host $http_host;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $host;
              proxy_set_header Connection "upgrade";
              proxy_cache_bypass $http_upgrade;
            }
      spec:
        ingressClassName: nginx
        rules:
          - host: "{{ portal_hostname }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: user-portal
                      port:
                        number: 3000
