---
- name: prepare for database work
  ansible.builtin.include_role:
    name: db_staging
    tasks_from: prepare.yml

- name: setup and migrate de databases
  ansible.builtin.include_tasks: de.yml

- name: setup and migrate grouper database
  when: grouper
  ansible.builtin.include_tasks: grouper.yml

- name: setup and migrate qms database
  when: qms
  ansible.builtin.include_tasks: qms.yml

- name: setup and migrate unleash database
  when: unleash
  ansible.builtin.include_tasks: unleash.yml

- name: setup and migrate harbor databases
  when: harbor
  ansible.builtin.include_tasks: harbor.yml

- name: setup and migrate keycloak databases
  when: keycloak
  ansible.builtin.include_tasks: keycloak.yml

- name: setup and migrate portal database
  when: portal
  ansible.builtin.include_tasks: portal.yml

- name: clean up database work
  ansible.builtin.include_role:
    name: db_staging
    tasks_from: cleanup.yml
