---
- ansible.builtin.include_tasks: prepare.yml
- ansible.builtin.include_tasks: de.yml
- ansible.builtin.include_tasks: grouper.yml
- ansible.builtin.include_tasks: qms.yml
- ansible.builtin.include_tasks: unleash.yml
- ansible.builtin.include_tasks: harbor.yml
- ansible.builtin.include_tasks: keycloak.yml
- ansible.builtin.include_tasks: cleanup.yml
