---
- delegate_to:
  block:
    - name: create qms database
      community.postgresql.postgresql_db:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        name: "{{ qms_db_name }}"
        owner: "{{ dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"
      when: create_dbs is defined and create_dbs and qms is defined and qms

    - name: install extensions for the qms database
      when: install_exts is defined and install_exts and qms is defined and qms
      community.postgresql.postgresql_ext:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        db: "{{ qms_db_name }}"
        name: "uuid-ossp"
      loop:
        - uuid-ossp
        - moddatetime
        - btree_gist
        - insert_username

    - name: checkout the qms repo for its migrations
      ansible.builtin.git:
        repo: "https://github.com/cyverse/qms"
        dest: "{{ dbs_dir.path }}/qms"
        clone: yes
        update: yes
        force: yes
        version: "{{ qms_version }}"

    - name: run qms repo for its migrations
      ansible.builtin.command: >
        {{migrate_installed.stdout}}
        -database "postgresql://{{dbms_connection_user}}:{{dbms_connection_pass}}@{{ groups['dbms'][0] }}:{{ pg_listen_port }}/qms?sslmode=disable"
        -path "{{ dbs_dir.path }}/qms/migrations"
        up
      when: migrate is defined and migrate
