---
- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
    - role: postgresql
    - role: postgresql_access
  tags:
    - install-postgres
    - databases

- name: initialize dbs
  hosts: dbms
  become: false
  connection: local
  roles:
    - role: postgresql_init
  tags:
    - setup-databases
    - databases

- name: install GPU drivers
  hosts: k8s_gpu_workers
  become: true
  roles:
    - nvidia_drivers
  tags:
    - install-gpu-drivers
    - prep-nodes
    - add-nodes

# so they can register through the load-balancer, otherwise
# they won't be able to use it.
- name: set the HAProxy load balancer
  hosts: k8s_api_proxy
  become: true
  roles:
    - role: haproxy
    - role: k8s_haproxy
  tags:
    - haproxy

- name: set up timezone settings.
  hosts: k8s_de_workers
  become: true
  gather_facts: true
  roles:
    - role: timezone
  tags:
    - timezone
    - prep-nodes
    - add-nodes

- name: prepare the nodes
  hosts: k8s_nodes
  become: true
  roles:
    - role: k8s_nodes
  tags:
    - prep-nodes
    - add-nodes

- name: set up firewall
  hosts: k8s_nodes
  become: true
  roles:
    - role: k8s_firewalld
  tags:
    - prep-nodes
    - add-nodes
    - firewall

# Add a playbook/role to call 'k0sctl apply --config <path>'
- hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  become: false
  roles:
    - role: k8s_cluster
      tags:
        - create-cluster
        - add-nodes

    - role: k8s_de_reqs
      tags: de-reqs

    - role: service_configurations
      tags: configure-services

    - role: secret_loader
      tags:
        - configure-services
        - secrets

    - role: kubernetes_ingresses
      tags: ingresses

    - role: kubernetes_networking
      tags:
        - networking
        - nodeports

    - role: cert-manager
      tags: cert-manager

    - role: nats
      tags: nats

    - role: kubernetes_node_feature_discovery
      tags: feature-discovery

    - role: grouper_init
      tags: grouper

    - role: image_cache
      tags: image-cache

- name: install the nvidia conttainer toolkit
  hosts: k8s_gpu_workers
  become: true
  roles:
    - nvidia_container_toolkit
  tags:
    - post-k8s-tasks
    - prep-nodes
    - add-nodes

- name: create the irods-csi-driver plugin directory
  hosts: k8s_workers
  become: true
  gather_facts: false
  tasks:
    - name: create the plugin directory
      ansible.builtin.file:
        state: directory
        path: /var/lib/k0s/kubelet/plugins/irods.csi.cyverse.org/
        recurse: true
  tags:
    - irods-csi-driver
    - prep-nodes
    - add-nodes

- name: create the irods-csi-driver plugins_registry directory
  hosts: k8s_workers
  become: true
  gather_facts: false
  tasks:
    - name: create the plugin directory
      ansible.builtin.file:
        state: directory
        path: /var/lib/k0s/kubelet/plugins_registry/
        recurse: true
  tags:
    - irods-csi-driver
    - prep-nodes
    - add-nodes

- name: set up irods-csi-driver
  hosts: k8s_controllers[0]
  connection: local
  become: false
  roles:
    - role: kubernetes_irods_csi_driver
  tags:
    - irods-csi-driver

- hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  become: false
  tags:
    - deploy-single-service
    - deploy-all-services
  tasks:
    - ansible.builtin.include_role:
        name: services
        tasks_from: main
      vars:
        project_name: "{{ project }}"
      tags:
        - deploy
      when: "'deploy-single-service' in ansible_run_tags"

    - ansible.builtin.include_role:
        name: services
        tasks_from: main
      vars:
        project_name: "{{ item }}"
      tags:
        - deploy
      when: "not 'deploy-single-service' in ansible_run_tags"
      with_items:
        - analyses
        - app-exposer
        - apply-labels
        - apps
        - async-tasks
        - bulk-typer
        - check-resource-access
        - clockwork
        - data-info
        - de-mailer
        - de-webhooks
        - dewey
        - discoenv-analyses
        - discoenv-users
        - email-requests
        - event-recorder
        - get-analysis-id
        - group-propagator
        - info-typer
        - infosquito2
        - iplant-groups
        - jex-adapter
        - job-status-listener
        - job-status-recorder
        - job-status-to-apps-adapter
        - kifshare
        - metadata
        - notifications
        - permissions
        - qms
        - qms-adapter
        - requests
        - resource-usage-api
        - data-usage-api
        - subscriptions
        - timelord
        - user-info
        - vice-default-backend
        - vice-status-listener
        - search
        - dashboard-aggregator
        - terrain
        - sonora
        - portal-ldap
        - portal-datastore
        - portal-conductor
        - portal2

- name: set up UI haproxy
  become: true
  hosts: de_haproxy
  roles:
    - role: ui_haproxy
  tags:
    - haproxy
    - ui-haproxy

- name: set up cronjobs
  become: false
  gather_facts: false
  hosts: k8s_controllers[0]
  connection: local
  roles:
    - role: cronjobs
      tags: cronjobs

    - role: keycloak_install
      tags: keycloak
      when: "'keycloak' in ansible_run_tags"

    - role: harbor
      tags: harbor
      when: "'harbor' in ansible_run_tags"

    - role: jaeger
      tags: jaeger
      when: "'jaeger' in ansible_run_tags"

    - role: argo
      tags: argo

    - role: argo_resources
      tags:
        - argo-resources
        - argo
